/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.chef.view;

import java.awt.List;
import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.text.SimpleDateFormat;
import java.util.Date;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.chef.controller.ChefController;
import lk.ijse.chef.controller.OrderController;
import lk.ijse.chef.dto.AddChefDTO;
import lk.ijse.chef.dto.ChefDTO;
import lk.ijse.chef.dto.OrdersDTO;
import lk.ijse.chef.observer.Observer;

/**
 *
 * @author Thilini Hansika
 */
public class ChefForm extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form ChefForm
     */
    private DefaultTableModel dtm = null;

    public ChefForm() {

        initComponents();
        loadSystemDate();
        loadChefCombo();
        try {
            dtm = (DefaultTableModel) tblOrder.getModel();
            UnicastRemoteObject.exportObject(this, 0);
            try {
                OrderController.getSubject().registerObserver(this);
            } catch (Exception ex) {
                Logger.getLogger(ChefForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(ChefForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnTake = new javax.swing.JButton();
        btnFinished = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtChefId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAty = new javax.swing.JTextField();
        txtNo = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtOid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCusName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrder = new org.jdesktop.swingx.JXTable();
        txtDate = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbChefName = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jXTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel1.setText("Chef-Appliction");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 280, 40));

        btnTake.setBackground(new java.awt.Color(0, 102, 102));
        btnTake.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnTake.setForeground(new java.awt.Color(255, 255, 255));
        btnTake.setText("Take Order");
        btnTake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTakeMouseClicked(evt);
            }
        });
        btnTake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTakeActionPerformed(evt);
            }
        });
        jPanel1.add(btnTake, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 580, 50));

        btnFinished.setBackground(new java.awt.Color(102, 102, 102));
        btnFinished.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnFinished.setForeground(new java.awt.Color(255, 255, 255));
        btnFinished.setText("Finished Order");
        btnFinished.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinishedMouseClicked(evt);
            }
        });
        btnFinished.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishedActionPerformed(evt);
            }
        });
        jPanel1.add(btnFinished, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 570, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Order Id");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 80, 20));

        txtChefId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChefIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtChefId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 170, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Chef Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 120, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Spent Time");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 110, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Prepared Bun");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 140, 20));
        jPanel1.add(txtAty, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 170, 30));
        jPanel1.add(txtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 170, 30));
        jPanel1.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, 160, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Contact No");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 100, 20));
        jPanel1.add(txtOid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 170, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Customer Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 150, 20));
        jPanel1.add(txtCusName, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 170, 30));

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Id", "Customer Name", "phone no", "qty"
            }
        ));
        jScrollPane2.setViewportView(tblOrder);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 590, 180));
        jPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 160, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Chef Id");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 70, 20));

        cmbChefName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbChefNameItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbChefName, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 170, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/chef/image/448c25a2160f6fe9571c1554bbcf4216--dude-perfect-stock-illustrations.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTakeActionPerformed
        try {

            //DefaultTableModel dtm = (DefaultTableModel) tblOrder.getModel();
            // dtm.setRowCount(0);
            //OrdersDTO od = ChefController.getOrder();
            // OrdersDTO odto=new OrdersDTO();
            //  java.util.List<OrdersDTO> list = OrderController.getAllList();
            // for (OrdersDTO o : list) {
            // for (OrdersDTO o : allOrders) {
            // System.out.println("A" + o);
            //Object[] rowdata = {o.getOid(), o.getCustomerName(), o.getPhone(), o.getQty()};
            // dtm.addRow(rowdata);
            OrdersDTO dTO = ChefController.getOrder();
            if (dTO == null) {
                JOptionPane.showMessageDialog(this, "No Orders");
            }
            txtOid.setText(Integer.toString(dTO.getOid()));
            txtCusName.setText(dTO.getCustomerName());
            txtNo.setText(dTO.getPhone());
            txtAty.setText(Integer.toString(dTO.getQty()));

        } catch (Exception ex) {
            Logger.getLogger(ChefForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTakeActionPerformed

    private void btnTakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTakeMouseClicked


    }//GEN-LAST:event_btnTakeMouseClicked

    private void btnFinishedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinishedMouseClicked
       /* OrderTiketForm o = new OrderTiketForm();
        o.setVisible(true);*/

    }//GEN-LAST:event_btnFinishedMouseClicked

    private void txtChefIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChefIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChefIdActionPerformed

    private void btnFinishedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishedActionPerformed

        int oid = Integer.parseInt(txtOid.getText());
        int chefId = Integer.parseInt(txtChefId.getText());
        String name = txtCusName.getText();

        int time = Integer.parseInt(txtTime.getText());
        String date = txtDate.getText();
        String bun = txtAty.getText();

        ChefDTO chef = new ChefDTO();
        chef.setOid(oid);
        chef.setChefID(chefId);
        chef.setDate(date);
        chef.setCustomerName(name);

        chef.setPreparedBun(bun);

        chef.setSpentTime(time);
        try {
            boolean isSave = ChefController.addOrder(chef);
           if (isSave) {
                JOptionPane.showMessageDialog(this, "Chef Order Added");
            } else {
                JOptionPane.showMessageDialog(this, "Sorry Unable to add this Order");
            }

        } catch (Exception ex) {
            Logger.getLogger(ChefForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFinishedActionPerformed

    private void cmbChefNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbChefNameItemStateChanged
        try {
            if (cmbChefName.getSelectedItem() == null) {
                return;
            }
            String chefName = cmbChefName.getSelectedItem().toString();
            AddChefDTO searchChefByName = ChefController.searchChefByName(chefName);

            txtChefId.setText(Integer.toString(searchChefByName.getChefId()));
        } catch (Exception ex) {
            Logger.getLogger(ChefForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_cmbChefNameItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChefForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChefForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChefForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChefForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChefForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinished;
    private javax.swing.JButton btnTake;
    private javax.swing.JComboBox<String> cmbChefName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXTable jXTable1;
    private org.jdesktop.swingx.JXTable tblOrder;
    private javax.swing.JTextField txtAty;
    private javax.swing.JTextField txtChefId;
    private javax.swing.JTextField txtCusName;
    private javax.swing.JLabel txtDate;
    private javax.swing.JTextField txtNo;
    private javax.swing.JTextField txtOid;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() throws RemoteException {
        try {
            // DefaultTableModel dtm = new DefaultTableModel();
            dtm.setRowCount(0);
            java.util.List<OrdersDTO> allList = OrderController.getAllList();
            for (OrdersDTO o : allList) {
                Object[] rowdata = {o.getOid(), o.getCustomerName(), o.getPhone(), o.getQty()};
                dtm.addRow(rowdata);
            }
        } catch (Exception ex) {
            Logger.getLogger(ChefForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadSystemDate() {
        Date date = new Date();
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("YYYY-MM-dd");
        String format = simpleDateFormat.format(date);
        txtDate.setText(format);
    }

    private void loadChefCombo() {
        try {
            java.util.List<AddChefDTO> allChefs = ChefController.getAllChef();
            for (AddChefDTO allChef : allChefs) {
                cmbChefName.addItem(allChef.getChefName());

            }
        } catch (Exception ex) {
            Logger.getLogger(ChefForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
