/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.chef.view;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.chef.controller.ChefController;
import lk.ijse.chef.controller.OrderController;
import lk.ijse.chef.dto.ChefDTO;
import lk.ijse.chef.dto.OrdersDTO;

/**
 *
 * @author Thilini Hansika
 */
public class PhoneForm extends javax.swing.JFrame {

    /**
     * Creates new form PhoneForm
     */
    public PhoneForm() {
        initComponents();
        loadSystemDate();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCusname = new javax.swing.JTextField();
        txtCustomerPhone = new javax.swing.JTextField();
        txtOpId = new javax.swing.JTextField();
        txtQty = new javax.swing.JTextField();
        btnSendKitchen = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtOid = new javax.swing.JTextField();
        txtDate = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 28)); // NOI18N
        jLabel1.setText("Operator Application");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 310, 31));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Customer Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 160, 31));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Order Qty");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 100, 31));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Mobile No");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 160, 31));
        jPanel1.add(txtCusname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 200, 30));
        jPanel1.add(txtCustomerPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 200, 30));
        jPanel1.add(txtOpId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 200, 30));

        txtQty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 200, 30));

        btnSendKitchen.setBackground(new java.awt.Color(0, 102, 102));
        btnSendKitchen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSendKitchen.setForeground(new java.awt.Color(255, 255, 255));
        btnSendKitchen.setText("SEND TO KITCHEN");
        btnSendKitchen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendKitchenActionPerformed(evt);
            }
        });
        jPanel1.add(btnSendKitchen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 370, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Order ID");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 134, 31));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Operator ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 134, 31));

        txtOid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOidActionPerformed(evt);
            }
        });
        jPanel1.add(txtOid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 200, 30));

        txtDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 160, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/chef/image/roll-2760504_960_720.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 480, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendKitchenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendKitchenActionPerformed
        OrdersDTO ordersDTO = new OrdersDTO();
        

        int oid = Integer.parseInt(txtOid.getText());
        String opID = txtOpId.getText();
        String date = txtDate.getText();
        String name = txtCusname.getText();
        String no = txtCustomerPhone.getText();
        int qty = Integer.parseInt(txtQty.getText());

        ordersDTO.setOid(oid);
        ordersDTO.setOperatorID(opID);
        ordersDTO.setOdate(date);
        ordersDTO.setCustomerName(name);
        ordersDTO.setPhone(no);
        ordersDTO.setQty(qty);

        try {
            boolean isAdded = OrderController.addOrderToQueue(ordersDTO);
            boolean isSave = ChefController.addOrder(ordersDTO);

            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Add to the Queue");
            } else {
                JOptionPane.showMessageDialog(this, "fail");
            }
        } catch (Exception ex) {
            Logger.getLogger(PhoneForm.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnSendKitchenActionPerformed

    private void txtOidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhoneForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhoneForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhoneForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhoneForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhoneForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendKitchen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCusname;
    private javax.swing.JTextField txtCustomerPhone;
    private javax.swing.JLabel txtDate;
    private javax.swing.JTextField txtOid;
    private javax.swing.JTextField txtOpId;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables
 private void loadSystemDate() {
        Date date = new Date();
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("YYYY-MM-dd");
        String format = simpleDateFormat.format(date);
        txtDate.setText(format);
    }

}
